"""initial_schema

Revision ID: df12640c1aa2
Revises: 
Create Date: 2026-04-02 16:30:36.112152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df12640c1aa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tracked_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('original_url', sa.String(length=2000), nullable=False),
    sa.Column('url_template', sa.String(length=2000), nullable=True),
    sa.Column('chapter_regex', sa.String(length=500), nullable=True),
    sa.Column('pattern_source', sa.Enum('AUTO', 'MANUAL', name='patternsource'), nullable=False),
    sa.Column('check_strategy', sa.Enum('INCREMENTAL_PROBE', name='checkstrategy'), nullable=False),
    sa.Column('current_chapter', sa.String(length=50), nullable=True),
    sa.Column('latest_chapter', sa.String(length=50), nullable=True),
    sa.Column('check_interval_min', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_check_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_latest_chapter', sa.String(length=50), nullable=True),
    sa.Column('new_latest_chapter', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['tracked_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_check_logs')
    op.drop_table('tracked_items')
    op.drop_table('users')
    # ### end Alembic commands ###
